In [31]:
#Import dependenices
import csv
import pandas as pd
from pathlib import Path
import hvplot.pandas
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import tensorflow as tfm
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import train_test_split

In [32]:
# Specify the path to your CSV file
csv_file_path = 'Resources/Clean_train.csv'

# Read the CSV file into a DataFrame
loan_data = pd.read_csv(csv_file_path)

#Print size of data set
print(loan_data.shape)

# Display the DataFrame
loan_data.head(5)

(80683, 15)


Current loan amount  Credit score  Annual income  Monthly debt  \
0             445412.0         709.0      1167493.0       5214.74   
1           99999999.0         741.0      2231892.0      29200.53   
2             347666.0         721.0       806949.0       8741.90   
3             206602.0        7290.0       896857.0      16367.74   
4             217646.0         730.0      1184194.0      10855.08   

   Years of credit history  Number of open accounts  \
0                     17.2                      6.0   
1                     14.9                     18.0   
2                     12.0                      9.0   
3                     17.3                      6.0   
4                     19.6                     13.0   

   Number of credit problems  Current credit balance  Maximum open credit  \
0                        1.0                228190.0             416746.0   
1                        1.0                297996.0             750090.0   
2                        0.0                256329.0             386958.0   
3                        0.0                215308.0             272448.0   
4                        1.0                122170.0             272052.0   

   Long term  Short term  Home mortgage  Own home  Rent  Bankrupt  
0          0           1              1         0     0         0  
1          0           1              0         1     0         0  
2          1           0              0         1     0         0  
3          0           1              1         0     0         0  
4          0           1              1         0     0         0

In [33]:
# Import the module
from sklearn.preprocessing import StandardScaler

In [34]:
# Scaling the numeric columns
data_scaled = StandardScaler().fit_transform(loan_data[['Current loan amount', 'Credit score', 'Annual income','Monthly debt','Years of credit history','Number of open accounts', 'Number of credit problems','Current credit balance','Maximum open credit']])

# Review the scaled data
data_scaled

array([[-4.03050203e-01, -2.48996183e-01, -1.95064699e-01, ...,
         1.69937754e+00, -1.75311853e-01, -4.60753246e-02],
       [ 2.45806717e+00, -2.27301607e-01,  7.89666434e-01, ...,
         1.69937754e+00,  7.62938426e-03,  2.27017159e-03],
       [-4.05859343e-01, -2.40860717e-01, -5.28622793e-01, ...,
        -3.48918343e-01, -1.01567712e-01, -5.03955333e-02],
       ...,
       [-4.12886935e-01, -2.26623651e-01, -2.10744180e-01, ...,
         1.69937754e+00, -4.86222327e-01, -2.85551874e-02],
       [-4.00609671e-01, -2.23911829e-01,  3.13797720e-01, ...,
        -3.48918343e-01,  2.86024718e-01,  5.53574639e-04],
       [ 2.45806717e+00, -2.25945696e-01, -4.09989595e-01, ...,
         1.69937754e+00, -6.53827173e-01, -9.33168384e-02]])

In [35]:
# Create a DataFrame of the scaled data
data_scaled = pd.DataFrame(data_scaled, columns=['Current loan amount', 'Credit score', 'Annual income','Monthly debt','Years of credit history','Number of open accounts', 'Number of credit problems','Current credit balance','Maximum open credit'])

# Create copy of the orginal dataframe
loan_data_copy = loan_data.copy()

# Replace the original data with the columns of information from the scaled Data
loan_data['Current loan amount'] = data_scaled['Current loan amount']
loan_data['Credit score'] = data_scaled['Credit score']
loan_data['Annual income'] = data_scaled['Annual income']
loan_data['Monthly debt'] = data_scaled['Monthly debt']
loan_data['Years of credit history'] = data_scaled['Years of credit history']
loan_data['Number of open accounts'] = data_scaled['Number of open accounts']
loan_data['Number of credit problems'] = data_scaled['Number of credit problems']
loan_data['Current credit balance'] = data_scaled['Current credit balance']
loan_data['Maximum open credit'] = data_scaled['Maximum open credit']

# Review the DataFrame
loan_data.head()

Current loan amount  Credit score  Annual income  Monthly debt  \
0            -0.403050     -0.248996      -0.195065     -1.088060   
1             2.458067     -0.227302       0.789666      0.872983   
2            -0.405859     -0.240861      -0.528623     -0.799685   
3            -0.409913      4.212629      -0.445444     -0.176207   
4            -0.409596     -0.234759      -0.179614     -0.626914   

   Years of credit history  Number of open accounts  \
0                -0.139697                -1.023574   
1                -0.467973                 1.363133   
2                -0.881886                -0.426898   
3                -0.125424                -1.023574   
4                 0.202852                 0.368672   

   Number of credit problems  Current credit balance  Maximum open credit  \
0                   1.699378               -0.175312            -0.046075   
1                   1.699378                0.007629             0.002270   
2                  -0.348918               -0.101568            -0.050396   
3                  -0.348918               -0.209072            -0.067003   
4                   1.699378               -0.453159            -0.067061   

   Long term  Short term  Home mortgage  Own home  Rent  Bankrupt  
0          0           1              1         0     0         0  
1          0           1              0         1     0         0  
2          1           0              0         1     0         0  
3          0           1              1         0     0         0  
4          0           1              1         0     0         0

In [36]:
# Export scaled data
csv_file_path = 'Resources/Cl.csv'

loan_data.to_csv(csv_file_path, index=False)

# Machine Learning

### Random Forest Model

In [ ]:
from pathlib import Path
from sklearn import tree

In [9]:
# Specify the path to your CSV file
csv_file_path = 'Resources/Clean_train_scaled.csv'

# Read the CSV file into a DataFrame
loan_data_rf = pd.read_csv(csv_file_path)

#Print size of data set
print(loan_data_rf.shape)

# Display the DataFrame
loan_data_rf.head(5)

(80683, 15)


Current loan amount  Credit score  Annual income  Monthly debt  \
0            -0.403050     -0.248996      -0.195065     -1.088060   
1             2.458067     -0.227302       0.789666      0.872983   
2            -0.405859     -0.240861      -0.528623     -0.799685   
3            -0.409913      4.212629      -0.445444     -0.176207   
4            -0.409596     -0.234759      -0.179614     -0.626914   

   Years of credit history  Number of open accounts  \
0                -0.139697                -1.023574   
1                -0.467973                 1.363133   
2                -0.881886                -0.426898   
3                -0.125424                -1.023574   
4                 0.202852                 0.368672   

   Number of credit problems  Current credit balance  Maximum open credit  \
0                   1.699378               -0.175312            -0.046075   
1                   1.699378                0.007629             0.002270   
2                  -0.348918               -0.101568            -0.050396   
3                  -0.348918               -0.209072            -0.067003   
4                   1.699378               -0.453159            -0.067061   

   Bankruptcies  Long term  Short term  Home mortgage  Own home  Rent  
0           1.0          0           1              1         0     0  
1           0.0          0           1              0         1     0  
2           0.0          1           0              0         1     0  
3           0.0          0           1              1         0     0  
4           1.0          0           1              1         0     0

In [10]:
# Define features set
X = loan_data_rf.copy()
X.drop("Bankruptcies", axis=1, inplace=True)
X.head()

Current loan amount  Credit score  Annual income  Monthly debt  \
0            -0.403050     -0.248996      -0.195065     -1.088060   
1             2.458067     -0.227302       0.789666      0.872983   
2            -0.405859     -0.240861      -0.528623     -0.799685   
3            -0.409913      4.212629      -0.445444     -0.176207   
4            -0.409596     -0.234759      -0.179614     -0.626914   

   Years of credit history  Number of open accounts  \
0                -0.139697                -1.023574   
1                -0.467973                 1.363133   
2                -0.881886                -0.426898   
3                -0.125424                -1.023574   
4                 0.202852                 0.368672   

   Number of credit problems  Current credit balance  Maximum open credit  \
0                   1.699378               -0.175312            -0.046075   
1                   1.699378                0.007629             0.002270   
2                  -0.348918               -0.101568            -0.050396   
3                  -0.348918               -0.209072            -0.067003   
4                   1.699378               -0.453159            -0.067061   

   Long term  Short term  Home mortgage  Own home  Rent  
0          0           1              1         0     0  
1          0           1              0         1     0  
2          1           0              0         1     0  
3          0           1              1         0     0  
4          0           1              1         0     0

In [11]:
# Define target vector
y = loan_data_rf["Bankruptcies"].values.reshape(-1, 1)
y[:5]

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.]])

In [23]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [24]:
# Creating the decision tree classifier instance
model = tree.DecisionTreeClassifier()

In [25]:
# Fitting the model
model = model.fit(X_train, y_train)

In [26]:
# Making predictions using the testing data
predictions = model.predict(X_test)
predictions

array([0., 0., 0., ..., 0., 1., 0.])

In [28]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[17601,   275,    22,     6,     2,     0,     0],
       [  288,  1839,    22,     3,     0,     0,     0],
       [   22,    14,    41,     0,     1,     0,     0],
       [    9,    10,     0,     9,     0,     0,     0],
       [    4,     0,     0,     1,     0,     0,     0],
       [    1,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     1]])

### Neural Network Model

### Ensemble Model

In [30]:
# Step 1: Read the Clean_train_scaled.csv data from the Resources folder into a Pandas DataFrame.

In [ ]:
# Specify the path to your CSV file
csv_file_path = 'Resources/Clean_train_scaled.csv'

# Read the CSV file into a DataFrame
loan_data = pd.read_csv(csv_file_path)

#Print size of data set
print(loan_data.shape)

# Display the DataFrame
loan_data.head(5)

In [ ]:
# Step 2: Create the labels set (y) from the “Rent” column, and then create the features (X) DataFrame from the remaining columns.

In [ ]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = loan_data['Rent']

# Separate the X variable, the features
X = loan_data.drop(columns=['Rent'])

In [ ]:
# Review the y variable Series
y.head()

In [ ]:
# Review the X variable DataFrame
X.head()

In [ ]:
# Check the balance of our target values
y.value_counts()

In [ ]:
# Step 3: Split the data into training and testing datasets by using train_test_split.

In [ ]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
# Create a Logistic Regression Model with the Original Data
# Step 1:Fit a logistic regression model by using the training data (X_train and y_train).

In [ ]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_model = LogisticRegression(solver='lbfgs', random_state=1)

# Fit the model using training data
lr_model = logistic_regression_model.fit(X_train, y_train)

In [ ]:
Step 2: Save the predictions on the testing data labels by using the testing feature data (X_test) and the fitted model.

In [ ]:
# Make a prediction using the testing data
LR_predictions = lr_model.predict(X_test)

In [ ]:
# Make a prediction using the testing data
test_predictions = logistic_regression_model.predict(X_test)
pd.DataFrame({'Predictions': test_predictions, 'Actual': y_test})

In [ ]:
Step 3: Evaluate the model’s performance by doing the following:
1. Generate Confusion Matrix
2. Print Classification report

In [ ]:
# Generate a confusion matrix for the model
cf_test_matrix = confusion_matrix(y_test, test_predictions)
cf_test_matrix 

In [ ]:
cm_imbalanced = confusion_matrix(y_test, LR_predictions)
cm_imbalanced_df = pd.DataFrame(cm_imbalanced, 
                                index = ['Actual Healthy Loans (low-risk)', 
                                'Actual Non-Healthy Loans (high-risk)'], 
                                columns = ['Predicted Healthy Loans (low-risk)', 'Predicted Non-Healthy Loans (high-risk)']
                              )
cm_imbalanced_df

In [ ]:
# Print the classification report for the model
testing_report = classification_report(y_test, test_predictions)
print(testing_report)

In [ ]:
My balanced accuracy score is an impressive 100%!  It takes into account both sensitivity (true positive rate) and specificity 
(true negative rate) to measure the performance of my model, especially when dealing with imbalanced datasets. With 46,682 rejected
loans and only 34,001 accepted ones. It’s important to have metric that considers this imbalance.

And guess what? My model’s accuracy score is a whopping 100% That means it correctly predicted 100% of all loans in the dataset.That’s 
pretty incredible right?

Looking at the confusion matrix my model did a great job by accepting 11,770 healthy loans and rejecting 8,401 high-risk loans accurately.
They were no mistakes like rejecting healthy loans or accepting high-risk loans. Overall, the model is doing a fantastic job.

Precision and recall are also important measures. My model has a precision score of 100% for default loans and perfect 100% for healthy 
loans. This shows how well my prediction matched reality. And when it comes to recall which looks at how well reality matched the 
predictions my model scored 100% for default loans and 100% for healthy loans.

Finally, the F1 score. It’s the weighted average of precision and recall scores, and it is the great way to evaluate the overall 
performance of my model. F1 score is 100% for default loans 100% for healthy loans.

In [ ]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

In [ ]:
# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
ROS_model = RandomOverSampler(random_state = 1)

In [ ]:
# Fit the original training data to the random_oversampler model
X_oversampled, y_oversampled = ROS_model.fit_resample(X_train, y_train)

In [ ]:
# Count the distinct values of the resampled labels data
y_oversampled.value_counts()

In [ ]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
LR_oversampled_model = LogisticRegression(random_state = 1)

In [ ]:
# Fit the model using the resampled training data
LR_oversampled_model.fit(X_oversampled, y_oversampled)

In [ ]:
# Make a prediction using the testing data
LR_oversampled_pred = LR_oversampled_model.predict(X_test)

In [ ]:
# Print the balanced_accuracy score of the model 
balanced_accuracy_score(y_test, LR_oversampled_pred)

In [ ]:
# Generate a confusion matrix for the model
cm_oversampled = confusion_matrix(y_test, LR_oversampled_pred)
cm_oversampled_df = pd.DataFrame(cm_oversampled, 
                                index = ['Actual Healthy Loans (low-risk)', 
                                'Actual Non-Healthy Loans (high-risk)'], 
                                columns = ['Predicted Healthy Loans (low-risk)', 'Predicted Non-Healthy Loans (high-risk)']
                              )
cm_oversampled_df

In [ ]:
'''
-- Out of the 11,770 loan status's that are healthy, the model predicted 11,770 as 
   healthy correctly. 

-- Out of the 8,401 loan status's that are non-healthy (high-risk), the model 
   predicted 8,401 as non-healthy correctly.

In [ ]:
# Print the classification report for the model
print(classification_report(y_test, LR_oversampled_pred))

In [ ]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

rf_model = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

# Fitting the model
rf_model = rf_model.fit(X_train, y_train)

In [ ]:
# Calculated the balanced accuracy score
from sklearn.metrics import accuracy_score
y_pred = rf_model.predict(X_test)
acc_score = accuracy_score(y_test, y_pred)
print(acc_score)

In [ ]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix, classification_report

matrix = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    matrix, index=["Actual High-Risk", "Actual Low-Risk"], columns=["Predicted High_Risk", "Prediceted Low_Risk"])
cm_df

In [ ]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

In [ ]:
# List the features sorted in descending order by feature importance
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

In [ ]:
#Easy Ensemble AdaBoost Classifier

In [ ]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier

eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec.fit(X_train, y_train)

In [ ]:
# Calculated the balanced accuracy score
from sklearn.metrics import accuracy_score
y_pred = eec.predict(X_test)
acc_score2 = accuracy_score(y_test, y_pred)
print(acc_score2)

In [ ]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix, classification_report

cm_df = pd.DataFrame(
    matrix, index=["Actual High-Risk", "Actual Low-Risk"], columns=["Predicted High_Risk", "Prediceted Low_Risk"])
cm_df

In [ ]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

### XGBoost